### ISSUE TITLE
Missing await

### ISSUE THREAD

**Issue by jgrinols** [long2ice/asyncmy#12]
Ran into this error when using a BinLogStream:
BinLogStream: TypeError: '_asyncio.Future' object is not subscriptable

https://github.com/long2ice/asyncmy/blob/b458bd1b622f415e77e42bd64e41c872ebcbcbc8/asyncmy/replication/binlogstream.py#L200

**Comment by long2ice** [comment]
detail?

**Comment by long2ice** [comment]
Fixed
