### ISSUE TITLE
Fails on 3.10 - invalid argument loop

### ISSUE THREAD

**Issue by pds2208** [long2ice/asyncmy#15]
Python 3.10 has removed the use of the loop argument in async io. 

The issue is in line 512 and 522 in connection.pyx where it passes in the loop `loop=loop`. Running on 3.10 and later can be determined by:

`use_loop = True if sys.version_info < (3, 10) else False` 

and this can be used to decide whether to pass in the loop parameter or not.

**Comment by long2ice** [comment]
Fixed
