### ISSUE TITLE
Windows installation error

### ISSUE THREAD

**Issue by dkharyna** [long2ice/asyncmy#16]
I've followed up with [instruction](https://github.com/long2ice/asyncmy#installing-on-windows) but I'm still see an error below

>  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\ADCIKB9\ce-svc-studio-query\env\Scripts\python.exe' 'C:\Users\ADCIKB9\ce-svc-studio-query\env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\ADCIKB9\AppData\Local\
Temp\tmpirmgnked'
       cwd: C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f
  Complete output (93 lines):
  A setup.py file already exists. Using it.
  C:\Users\ADCIKB9\AppData\Local\Temp\pip-build-env-2jw0igmv\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later
 release! File: C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\asyncmy\charset.pxd
    tree = Parsing.p_module(s, pxd, full_module_name)
  C:\Users\ADCIKB9\AppData\Local\Temp\pip-build-env-2jw0igmv\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later
 release! File: C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\asyncmy\connection.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  C:\Users\ADCIKB9\AppData\Local\Temp\pip-build-env-2jw0igmv\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later
 release! File: C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\asyncmy\converters.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  warning: asyncmy\converters.pyx:284:6: cpdef variables will not be supported in Cython 3; currently they are no different from cdef variables
  C:\Users\ADCIKB9\AppData\Local\Temp\pip-build-env-2jw0igmv\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later
 release! File: C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\asyncmy\errors.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  C:\Users\ADCIKB9\AppData\Local\Temp\pip-build-env-2jw0igmv\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later
 release! File: C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\asyncmy\protocol.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  Compiling asyncmy\charset.pyx because it changed.
  Compiling asyncmy\connection.pyx because it changed.
  Compiling asyncmy\converters.pyx because it changed.
  Compiling asyncmy\errors.pyx because it changed.
  Compiling asyncmy\protocol.pyx because it changed.
  [1/5] Cythonizing asyncmy\charset.pyx
  [2/5] Cythonizing asyncmy\connection.pyx
  [3/5] Cythonizing asyncmy\converters.pyx
  [4/5] Cythonizing asyncmy\errors.pyx
  [5/5] Cythonizing asyncmy\protocol.pyx
  C:\Python39\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'language_level'
    warnings.warn(msg)
  running build
  running build_py
  creating C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build
  creating C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9
  creating C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\auth.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\contexts.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\cursors.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\optionfile.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\pool.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\version.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\__init__.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  creating C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\constants
  copying asyncmy\constants\CLIENT.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\constants
  copying asyncmy\constants\COLUMN.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\constants
  copying asyncmy\constants\COMMAND.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\constants
  copying asyncmy\constants\CR.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\constants
  copying asyncmy\constants\ER.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\constants
  copying asyncmy\constants\FIELD_TYPE.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\constants
  copying asyncmy\constants\FLAG.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\constants
  copying asyncmy\constants\SERVER_STATUS.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\constants
  copying asyncmy\constants\__init__.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\constants
  creating C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\binlogstream.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\bitmap.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\column.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\constants.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\errors.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\events.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\gtid.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\packets.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\row_events.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\table.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\utils.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\replication\__init__.py -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy\replication
  copying asyncmy\charset.c -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\charset.pxd -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\charset.pyx -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\connection.c -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\connection.pyx -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\converters.c -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\converters.pyx -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\errors.c -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\errors.pyx -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\protocol.c -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  copying asyncmy\protocol.pyx -> C:\Users\ADCIKB9\AppData\Local\Temp\pip-install-4402u2x5\asyncmy_54167abab12f424ba3058cc2db5ee13f\build\lib.win-amd64-3.9\asyncmy
  running build_ext
  building 'asyncmy.charset' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  Traceback (most recent call last):
    File "C:\Users\ADCIKB9\ce-svc-studio-query\env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
      main()
    File "C:\Users\ADCIKB9\ce-svc-studio-query\env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\ADCIKB9\ce-svc-studio-query\env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\ADCIKB9\AppData\Local\Temp\pip-build-env-2jw0igmv\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 68, in build_wheel
      return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory)))
    File "C:\Users\ADCIKB9\AppData\Local\Temp\pip-build-env-2jw0igmv\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 72, in make_in
      wb.build()
    File "C:\Users\ADCIKB9\AppData\Local\Temp\pip-build-env-2jw0igmv\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 103, in build
      self._build(zip_file)
    File "C:\Users\ADCIKB9\AppData\Local\Temp\pip-build-env-2jw0igmv\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 135, in _build
      self._run_build_command(setup)
    File "C:\Users\ADCIKB9\AppData\Local\Temp\pip-build-env-2jw0igmv\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 163, in _run_build_command
      subprocess.check_call(
    File "C:\Python39\lib\subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['C:/Users/ADCIKB9/ce-svc-studio-query/env/Scripts/python.exe', 'C:\\Users\\ADCIKB9\\AppData\\Local\\Temp\\pip-install-4402u2x5\\asyncmy_54167abab12f424ba3058cc2db5ee13f\\setup.py',
'build', '-b', 'C:\\Users\\ADCIKB9\\AppData\\Local\\Temp\\pip-install-4402u2x5\\asyncmy_54167abab12f424ba3058cc2db5ee13f\\build']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for asyncmy
Failed to build asyncmy
ERROR: Could not build wheels for asyncmy which use PEP 517 and cannot be installed directly

**Comment by long2ice** [comment]
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools":

Looks like can't found the tool

**Comment by synodriver** [comment]
> > Why not build use github action？See my branch.
> 
> @synodriver Hi, thanks for the wheels! Could I ask you to build wheels for the latest changes?

Sure. And I will send a pr to @long2ice later.

**Comment by dkharyna** [comment]
> > > Why not build use github action？See my branch.
> > 
> > 
> > @synodriver Hi, thanks for the wheels! Could I ask you to build wheels for the latest changes?
> 
> Sure. And I will send a pr to @long2ice later.

@synodriver Thanks a lot!
