### ISSUE TITLE
0.2.1 fails with FastAPI 0.7.0 / Python 3.10/ sqlmodel / SQLAlchemy

### ISSUE THREAD

**Issue by pds2208** [long2ice/asyncmy#18]
A simple fastapi application using python 3.10, which works with aiomysql (albeit with a patch to remove the loop argument on connect) fails with asyncmy.

```
  File "asyncmy/connection.pyx", line 373, in rollback
  File "asyncmy/connection.pyx", line 336, in _read_ok_packet
  File "asyncmy/connection.pyx", line 588, in read_packet
sqlalchemy.exc.InternalError: (asyncmy.errors.InternalError) Packet sequence number wrong - got 17 expected 1
```

The same code fails with both 3.9 and 3.10 using v 0.2.1 but is okay with 0.2.0 on 3.9 (obviously 3.10 fails with 0.2.0 due to the loop issue fixed in 0.2.1).

 So something in the 0.2.1 release is causing problems. Code is too long to paste but should be easy to replicate.

**Comment by pds2208** [comment]
No

**Comment by long2ice** [comment]
Add it then try again

**Comment by zzzeek** [comment]
i will get you a reproducer via our test suite momentarily

**Comment by long2ice** [comment]
Fixed, try it again, if no problem, I will release new version

**Comment by pds2208** [comment]
Yes working here. Please look at #14  - it's holding me back
