### ISSUE TITLE
cannot import error

### ISSUE THREAD

**Issue by ehsanonline** [long2ice/asyncmy#29]
Hello. I installed this using `pip` on python 3.8.10 and virtualenv, ubuntu 20.04, and it was installed successfully. But when I ran the first example code from the readme, I got this error from the line `from asyncmy import connect`:
`ImportError: cannot import name 'connect' from partially initialized module 'asyncmy' (most likely due to a circular import)`
There is no circular import, It's just a single file with the first example code copied. I commented that import line, then it shows this error for the next line `from asyncmy.cursors import DictCursor`:
`ModuleNotFoundError: No module named 'asyncmy.cursors'; 'asyncmy' is not a package`.

**Comment by long2ice** [comment]
What's you file name?

**Comment by ehsanonline** [comment]
Oh! Silly me! I named the file `asyncmy.py`, which was the problem. Thank you.
