### ISSUE TITLE
Use enum (or any type) as argumenets

### ISSUE THREAD

**Issue by Trim21** [long2ice/asyncmy#30]
I'm trying to build a query like  this `Table.column ==  TopicState.TOPIC_STATE_NONE`, but I got a `ValueError`

`TypeError: Argument 'value' has incorrect type (expected str, got TopicState)`

```text
  File "asyncmy\connection.pyx", line 426, in asyncmy.connection.Connection.literal
  File "asyncmy\connection.pyx", line 419, in asyncmy.connection.Connection.escape
  File "asyncmy\converters.pyx", line 10, in asyncmy.converters.escape_item
  File "asyncmy\converters.pyx", line 25, in asyncmy.converters.escape_item
TypeError: Argument 'value' has incorrect type (expected str, got TopicState)
```
To avoid this, I need to  `Table.column ==  TopicState.TOPIC_STATE_NONE.value` to get enum's underlying value.

In aiomysql, I can add a method `translate(self, _escape_table)` to support any type, is there any way in asyncmy we can do this?

**Comment by long2ice** [comment]
Could you give link for that?

**Comment by Trim21** [comment]
do you mean `translate`?

**Comment by long2ice** [comment]
Yes

**Comment by Trim21** [comment]
https://github.com/PyMySQL/PyMySQL/blob/f24cb9aa7295921bcd8f34f752c8a05b981d3125/pymysql/converters.py#L81

**Comment by Trim21** [comment]
didn't find doc about this, but it's raised in the exception message

**Comment by long2ice** [comment]
OK

**Comment by Trim21** [comment]
Maybe it's a undefined behavior? What ever, it would be a better way if we can use enum value directly.

**Comment by long2ice** [comment]
Fixed
