### ISSUE TITLE
Any plan to make it work with tortoise orm?

### ISSUE THREAD

**Issue by ygl-rg** [long2ice/asyncmy#5]
As title

Thx

**Comment by ryanrain2016** [comment]
@ygl-rg 
just install it. 
see code in `tortoise/backends/mysql/client.py`  line 5-12
```python
try:
    import asyncmy as mysql
    from asyncmy import errors
    from asyncmy.charset import charset_by_name
except ImportError:
    import aiomysql as mysql
    from pymysql.charset import charset_by_name
    from pymysql import err as errors
```

**Comment by long2ice** [comment]
That' right

**Comment by ygl-rg** [comment]
> @ygl-rg
> just install it.
> see code in `tortoise/backends/mysql/client.py` line 5-12
> 
> ```python
> try:
>     import asyncmy as mysql
>     from asyncmy import errors
>     from asyncmy.charset import charset_by_name
> except ImportError:
>     import aiomysql as mysql
>     from pymysql.charset import charset_by_name
>     from pymysql import err as errors
> ```

thx..is it all good?
