### ISSUE TITLE
Support for SQLAlchemy 2.0x style ?

### ISSUE THREAD

**Issue by Tumornator** [long2ice/asyncmy#6]
Could this driver be used along with new SQLAlchemy 2.0x style, considering that their page now says asyncio is now in BETA (v1.4.22)

**Comment by synackSA** [comment]
I second this

**Comment by long2ice** [comment]
What's the detail?

**Comment by synodriver** [comment]
You mean use it as the backend of mysql in sqlalchemy？However I only see aiomysql support in sqlalchemy yet. Some effort is needed to port this into sqlalchemy.

**Comment by Tumornator** [comment]
Yes, exactly @synodriver
It would be very helpful as this library has better results that aiomysql :))
Currently I am using both aiomysql + SQLAlchemy 2.x style and asyncmy without SQLAlchemy in different projects.
But with the slow updates on aiomysql, it would be really helpful to have an actively maintained project considering all the upcoming changes on SQLAlchemy 2.0x

Thank you :))

**Comment by synodriver** [comment]
This should be a feature request in sqlalchemy……I think. ~~Or you can switche to postgresql like me~~

**Comment by Tumornator** [comment]
Ok I will cross post there.

**Comment by Tumornator** [comment]
@synodriver, I put up a request in sqlalchemy repo [here](https://github.com/sqlalchemy/sqlalchemy/issues/6993)

> The general reply is that we have the capacity to support only the most used dialects. Maybe the asyncmy maintainers could provide an external dialect?

[Here](https://github.com/sqlalchemy/sqlalchemy/discussions/6893) is another discussion referencing the same

**Comment by long2ice** [comment]
Wait https://github.com/sqlalchemy/sqlalchemy/pull/7000

**Comment by long2ice** [comment]
supported
