### ISSUE TITLE
should Cursor.fetchone()  be async?

### ISSUE THREAD

**Issue by leofiore** [long2ice/asyncmy#7]
in the example provided on the README the code `res = await cursor.fetchone()` cannot work, since `fetchone()` [is not defined as async](https://github.com/long2ice/asyncmy/blob/dev/asyncmy/cursors.py#L297), and the same goes for `fetchmany`. On the other hand, `fetchone` and `fetchmany` are declared as async in the `SSCursor` implementation. I noticed it because i tried to use asyncmy as an aiomysql drop-in replacement, and using `fetchone` triggered the exception `TypeError: object tuple can't be used in 'await' expression`. I suppose those two methods should be declared as async?

**Comment by long2ice** [comment]
That's right, fixed.

**Comment by leofiore** [comment]
Thank you, works perfectly now.
