### ISSUE TITLE
[Question] Switching from aiomysql to asyncmy

### ISSUE THREAD

**Issue by R4zzerYT** [long2ice/asyncmy#9]
Hello, what exactly means "API compatible with aiomysql." ? Because I'm currently using it and want to switch to asyncmy but don't want to change many parts of my code for just database queries. The "wrong" errors I have in aiomysql are "`Task was destroyed, but it is pending!`" And "`An open stream object is being garbage collected; call “stream.close()” explicitly`".

So do I need to change code parts or means "API compatible with aiomysql" that I don't need to change anything, except from the import?

**Comment by long2ice** [comment]
In fact you need do nothing, what's error detail?

**Comment by R4zzerYT** [comment]
I closed the mydb Connection with "mydb.close()" and still got the error with the closing. And for the "Task was destroyed but it is pending part I build a async connection to MySQL and executed some queries everytime, the task runs. But the task can occur everytime and very fast.

**Comment by R4zzerYT** [comment]
I can give you the codes if it helps.

**Comment by long2ice** [comment]
OK, show me the code

**Comment by R4zzerYT** [comment]
https://stackoverflow.com/questions/68938011/aiomysql-discord-py-an-open-stream-object-is-being-garbage-collected-call-st

That's the code for the "stream.close()" error
